#!/bin/bash
#PBS -l nodes=1:ppn=12
#PBS -l walltime=24:00:00
#PBS -m abe
#PBS -M nsunkava@students.kennesaw.edu
#PBS -j oe

JOBID=`echo $PBS_JOBID | cut -f1 -d.`

module load MATLAB/R2023a MOSEK

# Create a temp workdir under scratch
mkdir -p ${HOME}/scratch/matlab
export PBS_MATLAB_WORKDIR=$( mktemp -d -p ${HOME}/scratch/matlab workdir_XXXXXXXXXX )

matlab -nodisplay -nosplash -logfile ${FILE}.log -r "run ${FILE}"

# Delete temp workdir
rm -rf ${PBS_MATLAB_WORKDIR}
